# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabs_thread.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabsThread(object):
    def setupUi(self, TabsThread):
        TabsThread.setObjectName("TabsThread")
        TabsThread.resize(526, 348)
        self.centralwidget = QtWidgets.QWidget(TabsThread)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(-7, 6, 525, 299))
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabs.setMovable(False)
        self.tabs.setObjectName("tabs")
        self.tabA = QtWidgets.QWidget()
        self.tabA.setObjectName("tabA")
        self.label_2 = QtWidgets.QLabel(self.tabA)
        self.label_2.setGeometry(QtCore.QRect(24, 15, 56, 13))
        self.label_2.setObjectName("label_2")
        self.te_chat = QtWidgets.QPlainTextEdit(self.tabA)
        self.te_chat.setGeometry(QtCore.QRect(15, 39, 399, 212))
        self.te_chat.setObjectName("te_chat")
        self.tabs.addTab(self.tabA, "")
        self.tabB = QtWidgets.QWidget()
        self.tabB.setObjectName("tabB")
        self.te_data = QtWidgets.QPlainTextEdit(self.tabB)
        self.te_data.setGeometry(QtCore.QRect(24, 43, 274, 182))
        self.te_data.setObjectName("te_data")
        self.label = QtWidgets.QLabel(self.tabB)
        self.label.setGeometry(QtCore.QRect(26, 15, 56, 13))
        self.label.setObjectName("label")
        self.tabs.addTab(self.tabB, "")
        self.tabC = QtWidgets.QWidget()
        self.tabC.setObjectName("tabC")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabC)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(36, 25, 147, 192))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.tabs.addTab(self.tabC, "")
        TabsThread.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TabsThread)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 22))
        self.menubar.setObjectName("menubar")
        self.menuTabs = QtWidgets.QMenu(self.menubar)
        self.menuTabs.setObjectName("menuTabs")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        TabsThread.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TabsThread)
        self.statusbar.setObjectName("statusbar")
        TabsThread.setStatusBar(self.statusbar)
        self.actionA = QtWidgets.QAction(TabsThread)
        self.actionA.setObjectName("actionA")
        self.actionB = QtWidgets.QAction(TabsThread)
        self.actionB.setObjectName("actionB")
        self.actionC = QtWidgets.QAction(TabsThread)
        self.actionC.setObjectName("actionC")
        self.actionQuit = QtWidgets.QAction(TabsThread)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStart_feed = QtWidgets.QAction(TabsThread)
        self.actionStart_feed.setObjectName("actionStart_feed")
        self.menuTabs.addAction(self.actionA)
        self.menuTabs.addAction(self.actionB)
        self.menuTabs.addAction(self.actionC)
        self.menuTabs.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionStart_feed)
        self.menubar.addAction(self.menuTabs.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TabsThread)
        self.tabs.setCurrentIndex(2)
        self.actionQuit.triggered.connect(TabsThread.close)
        QtCore.QMetaObject.connectSlotsByName(TabsThread)

    def retranslateUi(self, TabsThread):
        _translate = QtCore.QCoreApplication.translate
        TabsThread.setWindowTitle(_translate("TabsThread", "Tabs"))
        self.label_2.setText(_translate("TabsThread", "Chat"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabA), _translate("TabsThread", "A"))
        self.label.setText(_translate("TabsThread", "Data feed:"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabB), _translate("TabsThread", "B"))
        self.pushButton.setText(_translate("TabsThread", "Plan A"))
        self.pushButton_2.setText(_translate("TabsThread", "Plan B"))
        self.pushButton_3.setText(_translate("TabsThread", "Plan C"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabC), _translate("TabsThread", "C"))
        self.menuTabs.setTitle(_translate("TabsThread", "Tabs"))
        self.menuFile.setTitle(_translate("TabsThread", "File"))
        self.actionA.setText(_translate("TabsThread", "A"))
        self.actionB.setText(_translate("TabsThread", "B"))
        self.actionC.setText(_translate("TabsThread", "C"))
        self.actionQuit.setText(_translate("TabsThread", "Quit"))
        self.actionStart_feed.setText(_translate("TabsThread", "Start feed"))

